#!/usr/bin/env bash
# install-portals.sh — unified installer for clawlab admin portals
#
# Configures TLS (HTTP / HTTPS+LE / HTTPS existing), centralized claw-auth
# (SQLite) or legacy Linux PAM, nginx reverse proxies, and systemd user services.
#
# Usage:
#   ./install-portals.sh              # interactive
#   ./install-portals.sh --non-interactive --tls=https-le --auth=claw-auth
#
set -Eeuo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SRC/.." && pwd)"
# shellcheck source=../install/lib/clawlab-install-log.sh
source "$REPO/install/lib/clawlab-install-log.sh"
clawlab_install_log_begin "install-portals" "$@"
trap 'clawlab_install_log_end install-portals $?' EXIT

CONFIG_DIR="$HOME/.claw-portals"
CONFIG_FILE="$CONFIG_DIR/config.env"
UNIT_DIR="$HOME/.config/systemd/user"
NGINX_AVAILABLE="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

# Defaults (override via env or prompts)
LAN_IP="${LAN_IP:-192.168.1.10}"
DOMAIN="${DOMAIN:-lab.example.com}"
LE_EMAIL="${LE_EMAIL:-admin@example.com}"
TLS_MODE="${TLS_MODE:-}"          # http | https-le | https-existing
AUTH_MODE="${AUTH_MODE:-}"        # claw-auth | pam
PORT_SSH_OPS="${PORT_SSH_OPS:-}"
PORT_OPENCLAW="${PORT_OPENCLAW:-}"
PORT_DEFENSECLAW="${PORT_DEFENSECLAW:-}"
LE_CERT="${LE_CERT:-$HOME/mcp/acme/lego/certificates/${DOMAIN}.crt}"
LE_KEY="${LE_KEY:-$HOME/mcp/acme/lego/certificates/${DOMAIN}.key}"
NON_INTERACTIVE=0
DEPLOY_NGINX_ONLY=0

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --non-interactive       Use env/defaults only (no prompts)
  --tls=MODE              http | https-le | https-existing
  --auth=MODE             claw-auth | pam
  --lan-ip=IP             LAN listen address
  --domain=NAME           TLS certificate domain
  --email=ADDR            Let's Encrypt registration email

Environment: LAN_IP, DOMAIN, LE_EMAIL, TLS_MODE, AUTH_MODE, PORT_* , LE_CERT, LE_KEY
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NON_INTERACTIVE=1 ;;
    --deploy-nginx-only) DEPLOY_NGINX_ONLY=1 ;;
    --tls=*) TLS_MODE="${1#*=}" ;;
    --auth=*) AUTH_MODE="${1#*=}" ;;
    --lan-ip=*) LAN_IP="${1#*=}" ;;
    --domain=*) DOMAIN="${1#*=}" ;;
    --email=*) LE_EMAIL="${1#*=}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
  shift
done

prompt() {
  local var="$1" prompt="$2" default="$3"
  if [[ "$NON_INTERACTIVE" -eq 1 ]]; then
    printf -v "$var" '%s' "${!var:-$default}"
    return
  fi
  read -r -p "$prompt [$default]: " reply
  printf -v "$var" '%s' "${reply:-$default}"
}

choose_tls() {
  if [[ -n "$TLS_MODE" ]]; then return; fi
  if [[ "$NON_INTERACTIVE" -eq 1 ]]; then TLS_MODE="https-le"; return; fi
  echo
  echo "TLS mode:"
  echo "  1) HTTPS with Let's Encrypt (recommended)"
  echo "  2) HTTPS with existing certificate paths"
  echo "  3) HTTP only (lab / no TLS)"
  read -r -p "Choose [1]: " choice
  case "${choice:-1}" in
    1) TLS_MODE="https-le" ;;
    2) TLS_MODE="https-existing" ;;
    3) TLS_MODE="http" ;;
    *) TLS_MODE="https-le" ;;
  esac
}

choose_auth() {
  if [[ -n "$AUTH_MODE" ]]; then return; fi
  if [[ "$NON_INTERACTIVE" -eq 1 ]]; then AUTH_MODE="claw-auth"; return; fi
  echo
  echo "Authentication:"
  echo "  1) claw-auth — lightweight SQLite user database (recommended)"
  echo "  2) pam       — Linux system accounts via PAM (legacy)"
  read -r -p "Choose [1]: " choice
  case "${choice:-1}" in
    1) AUTH_MODE="claw-auth" ;;
    2) AUTH_MODE="pam" ;;
    *) AUTH_MODE="claw-auth" ;;
  esac
}

set_default_ports() {
  if [[ "$TLS_MODE" == "http" ]]; then
    PORT_PORTAL="${PORT_PORTAL:-8083}"
  else
    PORT_PORTAL="${PORT_PORTAL:-8443}"
  fi
  PORT_SSH_OPS="$PORT_PORTAL"
  PORT_OPENCLAW="$PORT_PORTAL"
  PORT_DEFENSECLAW="$PORT_PORTAL"
}

scheme_for_mode() {
  if [[ "$TLS_MODE" == "http" ]]; then echo "http"; else echo "https"; fi
}

write_config_env() {
  install -d -m 0700 "$CONFIG_DIR"
  local internal_token=""
  if [[ -f "$CONFIG_FILE" ]]; then
    internal_token="$(grep -E '^CLAWLAB_INTERNAL_TOKEN=' "$CONFIG_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d "\"'" || true)"
  fi
  if [[ -z "$internal_token" ]]; then
    internal_token="$(openssl rand -hex 24 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(24))')"
  fi
  cat >"$CONFIG_FILE" <<EOF
# Generated by install-portals.sh — $(date -Iseconds)
TLS_MODE=$TLS_MODE
AUTH_MODE=$AUTH_MODE
LAN_IP=$LAN_IP
DOMAIN=$DOMAIN
LE_EMAIL=$LE_EMAIL
PORT_SSH_OPS=$PORT_PORTAL
PORT_OPENCLAW=$PORT_PORTAL
PORT_DEFENSECLAW=$PORT_PORTAL
PORT_PORTAL=$PORT_PORTAL
LE_CERT=$LE_CERT
LE_KEY=$LE_KEY
CLAW_AUTH_REQUIRED=$([[ "$AUTH_MODE" == "claw-auth" ]] && echo 1 || echo 0)
CLAW_AUTH_SECURE=$([[ "$TLS_MODE" == "http" ]] && echo 0 || echo auto)
CLAW_AUTH_PREFIX=/_claw_auth
SCHEME=$(scheme_for_mode)
CLAW_PORTAL_HUB_URL=$(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/
CLAW_PORTAL_SSH_OPS_PATH=/ssh-ops/
CLAW_PORTAL_OPENCLAW_PATH=/openclaw/
CLAW_PORTAL_DEFENSECLAW_PATH=/defenseclaw/
CLAW_PORTAL_SSH_OPS_URL=$(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/ssh-ops/
CLAW_PORTAL_OPENCLAW_URL=$(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/openclaw/
CLAW_PORTAL_DEFENSECLAW_URL=$(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/defenseclaw/
CLAW_PORTAL_SSH_OPS_PORT=${PORT_PORTAL}
CLAWLAB_VENV=${CLAWLAB_VENV:-$HOME/.clawlab/venv}
CLAW_PYTHON=${CLAW_PYTHON:-$CLAWLAB_VENV/bin/python}
CLAWLAB_INTERNAL_TOKEN=${internal_token}
EOF
  chmod 0600 "$CONFIG_FILE"
}

install_python_deps() {
  # shellcheck disable=SC1091
  CLAWLAB_REPO="$REPO" source "$SRC/ensure-venv.sh"
  ensure_clawlab_venv
}

install_systemd_user_unit() {
  local src="$1" name="$2" sed_expr="$3"
  install -d -m 0755 "$UNIT_DIR"
  sed "$sed_expr" "$src" >"$UNIT_DIR/$name"
}

start_user_service() {
  local unit="$1"
  systemctl --user daemon-reload
  systemctl --user enable --now "$unit"
}

install_claw_auth() {
  echo "==> Installing claw-auth"
  install_python_deps
  install_systemd_user_unit \
    "$REPO/claw-auth/claw-auth.service" \
    "claw-auth.service" \
    "s|%h/clawlab/claw-auth|$REPO/claw-auth|g"
  # Inject portal URLs from config
  grep -q '^EnvironmentFile=-.*claw-portals/config.env' "$UNIT_DIR/claw-auth.service" || true
  loginctl enable-linger "$USER" 2>/dev/null || true
  start_user_service claw-auth.service

  "$CLAW_PYTHON" -c "import sys; sys.path.insert(0, '$REPO/claw-auth'); import store; store.init_db(); print(store.user_count())" | {
    read -r count
    if [[ "${count:-0}" -eq 0 ]]; then
      echo "==> Create the first admin user for claw-auth"
      if [[ "$NON_INTERACTIVE" -eq 1 ]]; then
        echo "WARN: No users exist. Run: $CLAW_PYTHON $REPO/claw-auth/manage.py create-user admin"
      else
        "$CLAW_PYTHON" "$REPO/claw-auth/manage.py" create-user admin
      fi
    fi
  }
}

install_backend_services() {
  echo "==> Installing backend GUIs (loopback only)"
  install_python_deps
  install_systemd_user_unit \
    "$REPO/defenseclaw-webgui/defenseclaw-webgui.service" \
    "defenseclaw-webgui.service" \
    "s|%h/clawlab/defenseclaw-webgui|$REPO/defenseclaw-webgui|g"

  if ! grep -q 'claw-portals/config.env' "$UNIT_DIR/defenseclaw-webgui.service"; then
    sed -i '/^\[Service\]/a EnvironmentFile=-'"$CONFIG_FILE" "$UNIT_DIR/defenseclaw-webgui.service"
  fi

  start_user_service defenseclaw-webgui.service
  install_ssh_ops_quadlet
  echo "NOTE: OpenClaw gateway must already be running (openclaw-gateway.service)."
}

install_ssh_ops_quadlet() {
  echo "==> Updating ssh-ops Podman quadlet (unified portal :${PORT_PORTAL}/ssh-ops/)"
  local qdir="$HOME/.config/containers/systemd"
  install -d -m 0755 "$qdir"
  install -m 0644 "$REPO/quadlets/ssh-ops-gui.container" "$qdir/ssh-ops-gui.container"

  if command -v podman >/dev/null 2>&1; then
    echo "==> Rebuilding ssh-ops image (includes claw_auth_middleware)"
    podman build -t ssh-ops:latest "$REPO/ssh-ops-mcp"
    systemctl --user daemon-reload
    systemctl --user try-restart ssh-ops-gui.service 2>/dev/null \
      || systemctl --user restart ssh-ops-gui.service 2>/dev/null \
      || echo "WARN: start ssh-ops-gui manually after first quadlet install"
  else
    echo "WARN: podman not found — rebuild ssh-ops image manually:"
    echo "  podman build -t ssh-ops:latest $REPO/ssh-ops-mcp"
    echo "  systemctl --user restart ssh-ops-gui"
  fi
}

nginx_auth_claw_block() {
  cat <<'NGINX'
    location = /_claw_auth {
        return 302 /_claw_auth/login;
    }
    location = /_claw_auth/verify {
        internal;
        proxy_pass http://127.0.0.1:8780/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie;
    }
    location /_claw_auth/ {
        proxy_pass http://127.0.0.1:8780/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    error_page 401 = @claw_auth_login;
    location @claw_auth_login {
        return 302 /_claw_auth/login?next=$request_uri;
    }
NGINX
}

nginx_auth_pam_block() {
  local prompt="$1"
  cat <<NGINX
    auth_pam              "$prompt";
    auth_pam_service_name "openclaw-admin";
NGINX
}

nginx_tls_listen() {
  local port="$1"
  if [[ "$TLS_MODE" == "http" ]]; then
    echo "    listen ${LAN_IP}:${port};"
  else
    cat <<NGINX
    listen ${LAN_IP}:${port} ssl;
    ssl_certificate     ${LE_CERT};
    ssl_certificate_key ${LE_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
NGINX
  fi
}

nginx_claw_auth_request() {
  cat <<'NGINX'
        auth_request /_claw_auth/verify;
        auth_request_set $claw_user $upstream_http_x_auth_user;
        auth_request_set $claw_role $upstream_http_x_auth_role;
        proxy_set_header X-Auth-User $claw_user;
        proxy_set_header X-Auth-Role $claw_role;
        proxy_set_header X-Forwarded-User $claw_user;
NGINX
}

nginx_proxy_common() {
  cat <<'NGINX'
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host       $http_host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
NGINX
}

write_unified_portal_nginx() {
  local out="$NGINX_AVAILABLE/clawlab-portal.conf"
  rm -f "$NGINX_ENABLED/clawlab-ssh-ops.conf" "$NGINX_ENABLED/clawlab-openclaw.conf" \
        "$NGINX_ENABLED/clawlab-defenseclaw.conf" \
        "$NGINX_ENABLED/openclaw-control.conf" "$NGINX_ENABLED/ssh-ops-admin.conf" \
        "$NGINX_ENABLED/openclaw-admin.conf" "$NGINX_ENABLED/defenseclaw-admin.conf" \
        2>/dev/null || true

  {
    echo "map \$http_upgrade \$connection_upgrade { default upgrade; '' close; }"
    echo
    echo "server {"
    nginx_tls_listen "$PORT_PORTAL"
    echo "    server_name ${DOMAIN} lab-host ${LAN_IP};"
    echo
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then
      nginx_auth_claw_block
    else
      nginx_auth_pam_block "clawlab portal (Linux login)"
    fi
    echo
    echo "    client_max_body_size 50m;"
    echo
    echo "    location /clawlab-assets/ {"
    echo "        alias ${REPO}/docs/assets/;"
    echo "        access_log off;"
    echo "    }"
    echo "    location = /favicon.ico {"
    echo "        alias ${REPO}/docs/assets/favicon-32.png;"
    echo "        access_log off;"
    echo "    }"
    echo
    echo "    # Portal hub (tabbed UI)"
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then
      echo "    location = / {"
      nginx_claw_auth_request
      echo "        proxy_pass http://127.0.0.1:8780/;"
      nginx_proxy_common
      echo "    }"
      echo
      echo "    location /admin/ {"
      nginx_claw_auth_request
      echo "        proxy_pass http://127.0.0.1:8780/admin/;"
      nginx_proxy_common
      echo "    }"
    else
      echo "    location = / {"
      echo "        root ${REPO}/claw-portals;"
      echo "        try_files /portal-hub-static.html =404;"
      echo "    }"
    fi
    echo
    echo "    # Webex bot inbound (attachmentActions) — no claw-auth; verified by HMAC"
    echo "    location /ssh-ops/webex/hooks/ {"
    echo "        proxy_pass http://127.0.0.1:8765/webex/hooks/;"
    nginx_proxy_common
    echo "    }"
    echo
    echo "    # MCP / ssh-ops admin GUI (Podman :8765)"
    echo "    location /ssh-ops/ {"
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then nginx_claw_auth_request; fi
    echo "        proxy_pass http://127.0.0.1:8765/;"
    nginx_proxy_common
    echo "    }"
    echo
    echo "    # DefenseClaw policy editor (:8770)"
    echo "    location /defenseclaw/ {"
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then nginx_claw_auth_request; fi
    echo "        proxy_pass http://127.0.0.1:8770/;"
    nginx_proxy_common
    echo "    }"
    echo
    echo "    # OpenClaw Control UI (:18789) — preserve /openclaw/ path (gateway basePath)"
    echo "    # No claw-auth auth_request here: gateway token auth handles WS; nginx"
    echo "    # auth_request on upgrade often yields 1006 (abnormal close) in browsers."
    echo "    # Do NOT 301 /openclaw -> /openclaw/: browsers cannot complete WSS through redirects."
    echo "    location = /openclaw {"
    echo "        proxy_pass http://127.0.0.1:18789;"
    nginx_proxy_common
    echo "        proxy_buffering    off;"
    echo "        proxy_cache          off;"
    echo "        proxy_read_timeout  3600s;"
    echo "        proxy_send_timeout  3600s;"
    echo "    }"
    echo "    location /openclaw/ {"
    echo "        proxy_pass http://127.0.0.1:18789;"
    nginx_proxy_common
    echo "        proxy_buffering    off;"
    echo "        proxy_cache          off;"
    echo "        proxy_read_timeout  3600s;"
    echo "        proxy_send_timeout  3600s;"
    echo "    }"
    echo "}"
  } >"$out"

  ln -sf "$out" "$NGINX_ENABLED/clawlab-portal.conf"
  echo "Wrote unified portal $out (port ${PORT_PORTAL})"
}

write_nginx_site() {
  local name="$1" port="$2" backend="$3" pam_prompt="$4" extra_proxy="$5"
  local out="$NGINX_AVAILABLE/clawlab-${name}.conf"
  {
    echo "server {"
    nginx_tls_listen "$port"
    echo "    server_name ${DOMAIN} lab-host ${LAN_IP};"
    echo
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then
      nginx_auth_claw_block
    else
      nginx_auth_pam_block "$pam_prompt"
    fi
    echo
    echo "    client_max_body_size 50m;"
    echo
    echo "    location / {"
    if [[ "$AUTH_MODE" == "claw-auth" ]]; then
      echo "        auth_request /_claw_auth/verify;"
      echo "        auth_request_set \$claw_user \$upstream_http_x_auth_user;"
      echo "        auth_request_set \$claw_role \$upstream_http_x_auth_role;"
      echo "        proxy_set_header X-Auth-User \$claw_user;"
      echo "        proxy_set_header X-Auth-Role \$claw_role;"
      echo "        proxy_set_header X-Forwarded-User \$claw_user;"
    fi
    echo "        proxy_pass ${backend};"
    echo "        proxy_http_version 1.1;"
    echo "        proxy_set_header Upgrade    \$http_upgrade;"
    echo "        proxy_set_header Connection \$connection_upgrade;"
    echo "        proxy_set_header Host       \$http_host;"
    echo "        proxy_set_header X-Real-IP  \$remote_addr;"
    echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
    echo "        proxy_set_header X-Forwarded-Host \$http_host;"
    if [[ -n "$extra_proxy" ]]; then
      echo "$extra_proxy"
    fi
    echo "    }"
    echo "}"
  } >"$out"

  ln -sf "$out" "$NGINX_ENABLED/clawlab-${name}.conf"
  echo "Wrote $out"
}

deploy_nginx() {
  echo "==> Deploying nginx site configs (requires sudo)"
  if [[ "${EUID}" -ne 0 ]]; then
    export CONFIG_FILE REPO TLS_MODE AUTH_MODE LAN_IP DOMAIN LE_CERT LE_KEY
    export PORT_PORTAL PORT_SSH_OPS PORT_OPENCLAW PORT_DEFENSECLAW
    sudo -E bash "$0" --deploy-nginx-only
    return
  fi

  echo "==> Deploying nginx site configs (root)"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -o Acquire::Retries=3
  if [[ "$AUTH_MODE" == "pam" ]]; then
    apt-get install -y nginx libnginx-mod-http-auth-pam openssl
    install -m 0644 "$REPO/pam/openclaw-admin" /etc/pam.d/openclaw-admin
    usermod -aG shadow www-data 2>/dev/null || true
  else
    apt-get install -y nginx
  fi

  install -d -m 0755 "$NGINX_AVAILABLE" "$NGINX_ENABLED"
  write_unified_portal_nginx

  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
}

issue_le_cert_if_needed() {
  if [[ "$TLS_MODE" != "https-le" ]]; then return; fi
  if [[ -f "$LE_CERT" && -f "$LE_KEY" ]]; then
    echo "LE cert already present: $LE_CERT"
    return
  fi
  echo "==> Obtaining Let's Encrypt certificate"
  DOMAIN="$DOMAIN" LE_EMAIL="$LE_EMAIL" bash "$REPO/acme/issue-cert.sh"
}

# Re-exec entry for sudo nginx deploy (after helper functions are defined)
if [[ "${DEPLOY_NGINX_ONLY:-0}" -eq 1 ]]; then
  DEPLOY_USER="${SUDO_USER:-${USER:-clawlab}}"
  DEPLOY_HOME="$(getent passwd "$DEPLOY_USER" 2>/dev/null | cut -d: -f6 || echo "/home/$DEPLOY_USER")"
  : "${CONFIG_FILE:=$DEPLOY_HOME/.claw-portals/config.env}"
  : "${REPO:=$DEPLOY_HOME/clawlab}"
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  set_default_ports
  deploy_nginx
  exit 0
fi

choose_tls
choose_auth
prompt LAN_IP "LAN IP" "$LAN_IP"
prompt DOMAIN "TLS domain / hostname" "$DOMAIN"
if [[ "$TLS_MODE" == "https-le" || "$TLS_MODE" == "https-existing" ]]; then
  prompt LE_EMAIL "Let's Encrypt email" "$LE_EMAIL"
  LE_CERT="$HOME/mcp/acme/lego/certificates/${DOMAIN}.crt"
  LE_KEY="$HOME/mcp/acme/lego/certificates/${DOMAIN}.key"
  if [[ "$TLS_MODE" == "https-existing" ]]; then
    prompt LE_CERT "Certificate path" "$LE_CERT"
    prompt LE_KEY "Private key path" "$LE_KEY"
  fi
fi
set_default_ports

echo
echo "==> Summary"
echo "  TLS:        $TLS_MODE"
echo "  Auth:       $AUTH_MODE"
echo "  Portal hub: $(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/"
echo

install_python_deps
write_config_env
issue_le_cert_if_needed

if [[ "$AUTH_MODE" == "claw-auth" ]]; then
  install_claw_auth
else
  echo "==> Skipping claw-auth (PAM mode)"
fi

install_backend_services
deploy_nginx

if [[ "$AUTH_MODE" == "claw-auth" && -f "$REPO/admin-access/configure-portal-mcp-auth.sh" ]]; then
  echo "==> MCP identity proxy + OpenClaw MCP auth"
  bash "$REPO/admin-access/configure-portal-mcp-auth.sh"
fi

if [[ -f "$REPO/admin-access/install-clawlab-extras.sh" ]]; then
  echo "==> OpenClaw skills + IOS config archive"
  bash "$REPO/admin-access/install-clawlab-extras.sh" \
    || echo "WARN: install-clawlab-extras failed — run: bash $REPO/admin-access/install-clawlab-extras.sh"
fi

cat <<EOF

Done.

Portal hub (bookmark this):
  $(scheme_for_mode)://${DOMAIN}:${PORT_PORTAL}/

Tabs:
  OpenClaw          /openclaw/
  MCP Admin         /ssh-ops/
  DefenseClaw       /defenseclaw/

Auth: $AUTH_MODE
Config saved: $CONFIG_FILE

Manage claw-auth users:
  $CLAW_PYTHON $REPO/claw-auth/manage.py create-user USER
  $CLAW_PYTHON $REPO/claw-auth/manage.py list-users

Python venv: ${CLAWLAB_VENV:-$HOME/.clawlab/venv}

Logs:
  journalctl --user -u claw-auth -f
  journalctl --user -u defenseclaw-webgui -f

OpenClaw Control UI (subpath /openclaw/):
  python3 $REPO/claw-portals/apply-openclaw-portal.py
  systemctl --user restart openclaw-gateway
  For OpenClaw behind this portal (same-host nginx): python3 $REPO/admin-access/apply-token-portal.py

MCP authentication (identity proxy :8767):
  OpenClaw: open from hub ↗ (clawBind) — or PAT: bash $REPO/admin-access/set-openclaw-mcp-pat.sh
  Cursor / external clients: hub → MCP tokens → Bearer skops_… at $(scheme_for_mode)://${DOMAIN}:8767/mcp
  Re-sync after changes: bash $REPO/admin-access/configure-portal-mcp-auth.sh
EOF
