#!/usr/bin/env bash
# clawlab-local-full.sh — self-contained loopback stack (Mac / dev desktop).
# Sourced from install-clawstack.sh when MODE=local-full.
# Manage running services: bash install/local-full-ctl.sh {start|stop|status}
set -Eeuo pipefail

CLAWLAB_RUN="${CLAWLAB_RUN:-$HOME/.clawlab/run}"
CLAWLAB_NGINX="${CLAWLAB_NGINX:-$HOME/.clawlab/nginx}"
CLAWLAB_SSH_OPS_DATA="${CLAWLAB_SSH_OPS_DATA:-$HOME/.clawlab/ssh-ops/data}"
LOCAL_FULL_DOMAIN="${LOCAL_FULL_DOMAIN:-127.0.0.1}"
LOCAL_FULL_PORT="${LOCAL_FULL_PORT:-8083}"

clawlab_local_full_supported() {
  [[ "$CLAWLAB_PLATFORM" == "macos" || "$CLAWLAB_PLATFORM" == "linux" ]]
}

clawlab_local_full_write_config() {
  local repo="$1"
  local config_dir="$HOME/.claw-portals"
  local config_file="$config_dir/config.env"
  install -d -m 0700 "$config_dir"
  local internal_token=""
  if [[ -f "$config_file" ]]; then
    internal_token="$(grep -E '^CLAWLAB_INTERNAL_TOKEN=' "$config_file" 2>/dev/null | head -1 | cut -d= -f2- | tr -d "\"'" || true)"
  fi
  if [[ -z "$internal_token" ]]; then
    internal_token="$(openssl rand -hex 24 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(24))')"
  fi
  # shellcheck disable=SC1091
  CLAWLAB_REPO="$repo" source "$repo/claw-portals/ensure-venv.sh"
  ensure_clawlab_venv
  cat >"$config_file" <<EOF
# Generated by install-clawstack.sh (local-full) — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
TLS_MODE=http
AUTH_MODE=claw-auth
LAN_IP=127.0.0.1
DOMAIN=${LOCAL_FULL_DOMAIN}
PORT_SSH_OPS=${LOCAL_FULL_PORT}
PORT_OPENCLAW=${LOCAL_FULL_PORT}
PORT_DEFENSECLAW=${LOCAL_FULL_PORT}
PORT_PORTAL=${LOCAL_FULL_PORT}
CLAW_AUTH_REQUIRED=1
CLAW_AUTH_SECURE=0
CLAW_AUTH_PREFIX=/_claw_auth
SCHEME=http
CLAW_PORTAL_HUB_URL=http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/
CLAW_PORTAL_SSH_OPS_PATH=/ssh-ops/
CLAW_PORTAL_OPENCLAW_PATH=/openclaw/
CLAW_PORTAL_DEFENSECLAW_PATH=/defenseclaw/
CLAW_PORTAL_SSH_OPS_URL=http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/ssh-ops/
CLAW_PORTAL_OPENCLAW_URL=http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/openclaw/
CLAW_PORTAL_DEFENSECLAW_URL=http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/defenseclaw/
CLAW_PORTAL_SSH_OPS_PORT=${LOCAL_FULL_PORT}
CLAWLAB_VENV=${CLAWLAB_VENV:-$HOME/.clawlab/venv}
CLAW_PYTHON=${CLAW_PYTHON:-$CLAWLAB_VENV/bin/python}
CLAWLAB_INTERNAL_TOKEN=${internal_token}
CLAWLAB_REPO=${repo}
EOF
  chmod 0600 "$config_file"
}

clawlab_local_full_ensure_admin_user() {
  local repo="$1"
  # shellcheck disable=SC1090
  set -a; source "$HOME/.claw-portals/config.env"; set +a
  local count
  count="$("$CLAW_PYTHON" -c "import sys; sys.path.insert(0, '$repo/claw-auth'); import store; store.init_db(); print(store.user_count())")"
  if [[ "${count:-0}" -eq 0 ]]; then
    if [[ "${AUTO_DEFAULTS:-0}" -eq 1 ]]; then
      warn "No claw-auth users yet — create one:"
      info "  $CLAW_PYTHON $repo/claw-auth/manage.py create-user admin"
    else
      log "Portal login (claw-auth for http://${LOCAL_FULL_DOMAIN:-127.0.0.1}:${LOCAL_FULL_PORT:-8083}/)"
      "$CLAW_PYTHON" "$repo/claw-auth/manage.py" create-user admin \
        || warn "create-user failed — run: $CLAW_PYTHON $repo/claw-auth/manage.py create-user admin"
    fi
  fi
}

clawlab_local_full_write_nginx() {
  local repo="$1"
  local out="$CLAWLAB_NGINX/clawlab-portal.conf"
  mkdir -p "$CLAWLAB_NGINX/logs"
  cat >"$CLAWLAB_NGINX/nginx.conf" <<'NGINX'
worker_processes  1;
error_log logs/error.log warn;
pid logs/nginx.pid;
events { worker_connections 256; }
http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;
  include clawlab-portal.conf;
}
NGINX
  if [[ ! -f "$CLAWLAB_NGINX/mime.types" ]]; then
    for mt in /opt/homebrew/etc/nginx/mime.types /usr/local/etc/nginx/mime.types /etc/nginx/mime.types; do
      if [[ -f "$mt" ]]; then cp "$mt" "$CLAWLAB_NGINX/mime.types"; break; fi
    done
  fi
  cat >"$out" <<NGINX
map \$http_upgrade \$connection_upgrade { default upgrade; '' close; }

server {
    listen 127.0.0.1:${LOCAL_FULL_PORT};
    server_name ${LOCAL_FULL_DOMAIN} localhost;

    client_max_body_size 50m;

    location = /_claw_auth { return 302 /_claw_auth/login; }
    location = /_claw_auth/verify {
        internal;
        proxy_pass http://127.0.0.1:8780/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie \$http_cookie;
    }
    location /_claw_auth/ {
        proxy_pass http://127.0.0.1:8780/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
    error_page 401 = @claw_auth_login;
    location @claw_auth_login {
        return 302 /_claw_auth/login?next=\$request_uri;
    }

    location = / {
        auth_request /_claw_auth/verify;
        auth_request_set \$claw_user \$upstream_http_x_auth_user;
        auth_request_set \$claw_role \$upstream_http_x_auth_role;
        proxy_set_header X-Auth-User \$claw_user;
        proxy_set_header X-Auth-Role \$claw_role;
        proxy_set_header X-Forwarded-User \$claw_user;
        proxy_pass http://127.0.0.1:8780/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
    }
    location /admin/ {
        auth_request /_claw_auth/verify;
        auth_request_set \$claw_user \$upstream_http_x_auth_user;
        auth_request_set \$claw_role \$upstream_http_x_auth_role;
        proxy_set_header X-Auth-User \$claw_user;
        proxy_set_header X-Auth-Role \$claw_role;
        proxy_set_header X-Forwarded-User \$claw_user;
        proxy_pass http://127.0.0.1:8780/admin/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /ssh-ops/ {
        auth_request /_claw_auth/verify;
        auth_request_set \$claw_user \$upstream_http_x_auth_user;
        auth_request_set \$claw_role \$upstream_http_x_auth_role;
        proxy_set_header X-Auth-User \$claw_user;
        proxy_set_header X-Auth-Role \$claw_role;
        proxy_set_header X-Forwarded-User \$claw_user;
        proxy_pass http://127.0.0.1:8765/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
    }

    location /defenseclaw/ {
        auth_request /_claw_auth/verify;
        auth_request_set \$claw_user \$upstream_http_x_auth_user;
        auth_request_set \$claw_role \$upstream_http_x_auth_role;
        proxy_set_header X-Auth-User \$claw_user;
        proxy_set_header X-Auth-Role \$claw_role;
        proxy_set_header X-Forwarded-User \$claw_user;
        proxy_pass http://127.0.0.1:8770/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
    }

    location = /openclaw {
        proxy_pass http://127.0.0.1:18789;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
    location /openclaw/ {
        proxy_pass http://127.0.0.1:18789;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
NGINX
}

clawlab_local_full_apply_openclaw_portal() {
  local oc="$HOME/.openclaw/openclaw.json"
  [[ -f "$oc" ]] || die "missing $oc — run install-clawstack.sh first"
  [[ -f "$CLAWLAB_REPO/admin-access/apply-token-portal.py" ]] \
    || die "missing apply-token-portal.py"
  DOMAIN="$LOCAL_FULL_DOMAIN" PORT_PORTAL="$LOCAL_FULL_PORT" SCHEME=http \
    python3 "$CLAWLAB_REPO/admin-access/apply-token-portal.py" \
    || die "apply-token-portal.py failed — fix ~/.openclaw/openclaw.json and re-run"
}

clawlab_local_full_configure_mcp_identity() {
  local repo="$1"
  local oc="$HOME/.openclaw/openclaw.json"
  local ext_src="$repo/clawlab-extensions/clawlab-mcp-identity"
  local ext_dst="$HOME/.openclaw/extensions/clawlab-mcp-identity"
  [[ -f "$oc" && -d "$ext_src" ]] || return 0
  mkdir -p "$HOME/.openclaw/extensions"
  rm -rf "$ext_dst"
  cp -a "$ext_src" "$ext_dst"
  PROXY_URL="http://127.0.0.1:8767/mcp" CLAWLAB_REPO="$repo" python3 - <<PY
import json, os
from pathlib import Path
cfg = Path(os.path.expanduser("$oc"))
data = json.loads(cfg.read_text())
mcp = data.setdefault("mcp", {}).setdefault("servers", {}).setdefault("ssh-ops", {})
mcp["url"] = os.environ["PROXY_URL"]
mcp.setdefault("transport", "streamable-http")
plugins = data.setdefault("plugins", {})
allow = list(plugins.setdefault("allow", []))
if "clawlab-mcp-identity" not in allow:
    allow.append("clawlab-mcp-identity")
plugins["allow"] = allow
plugins.setdefault("entries", {}).setdefault("clawlab-mcp-identity", {})["enabled"] = True
paths = list(plugins.setdefault("load", {}).setdefault("paths", []))
ext = os.path.expanduser("$ext_dst")
if ext not in paths:
    paths.append(ext)
plugins["load"]["paths"] = paths
cfg.write_text(json.dumps(data, indent=2) + "\n")
print("MCP identity plugin enabled; ssh-ops url ->", mcp["url"])
PY
}

clawlab_local_full_register_mcp() {
  local repo="$1"
  local oc="$HOME/.openclaw/openclaw.json"
  [[ -f "$oc" ]] || return 0
  mkdir -p "$CLAWLAB_SSH_OPS_DATA"
  local hosts="$CLAWLAB_SSH_OPS_DATA/hosts.yaml"
  if [[ ! -f "$hosts" && -f "$repo/ssh-ops-mcp/hosts.example.yaml" ]]; then
    cp "$repo/ssh-ops-mcp/hosts.example.yaml" "$hosts"
  fi
  local token
  token="$(
    SSH_OPS_CONFIG="$hosts" \
    PYTHONPATH="$repo/ssh-ops-mcp" \
    python3 -c 'import secrets_store; print(secrets_store.ensure_mcp_token())' 2>/dev/null \
    || true
  )"
  [[ -n "$token" ]] || { warn "Could not read MCP token — set in ssh-ops Admin after install"; return 0; }
  python3 - "$oc" "$token" <<'PY'
import json, sys
p, token = sys.argv[1], sys.argv[2]
d = json.load(open(p))
entry = {
    "url": "http://127.0.0.1:8766/mcp",
    "transport": "streamable-http",
    "headers": {"Authorization": "Bearer " + token},
}
d.setdefault("mcp", {}).setdefault("servers", {})["ssh-ops"] = entry
json.dump(d, open(p, "w"), indent=1)
print("registered MCP ssh-ops -> http://127.0.0.1:8766/mcp")
PY
}

clawlab_install_local_full() {
  local repo="${1:-$CLAWLAB_REPO}"
  local ctl="$repo/install/local-full-ctl.sh"
  [[ -f "$ctl" ]] || die "missing $ctl"

  log "Local-full: loopback portal (http://127.0.0.1:${LOCAL_FULL_PORT}) + ssh-ops MCP"
  if ! clawlab_podman_ready 2>/dev/null; then
    warn "podman not ready — install/start podman first (see preinstall-check.sh --fix)"
    clawlab_podman_recommend | sed 's/^/    /'
  fi

  clawlab_local_full_write_config "$repo"
  clawlab_local_full_write_nginx "$repo"
  clawlab_local_full_apply_openclaw_portal

  if ! command -v nginx >/dev/null 2>&1; then
    warn "nginx not on PATH — portal hub needs reverse proxy"
    if [[ "$CLAWLAB_PKG" == "brew" ]]; then
      info "  installing nginx via brew..."
      brew install nginx || warn "brew install nginx failed — run manually: brew install nginx"
    else
      info "  brew install nginx"
    fi
  fi

  bash "$ctl" start
  clawlab_local_full_register_mcp "$repo"
  clawlab_local_full_configure_mcp_identity "$repo"
  clawlab_local_full_ensure_admin_user "$repo"

  info "Portal hub:  http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/"
  info "OpenClaw:    hub tab → Open OpenClaw ↗ (first visit: approve device on OpenClaw devices tab)"
  info "MCP Admin:   http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/ssh-ops/"
  info "DefenseClaw: http://${LOCAL_FULL_DOMAIN}:${LOCAL_FULL_PORT}/defenseclaw/"
  info "MCP API:     http://127.0.0.1:8766/mcp (identity proxy :8767 when running)"
  info "Verify:      bash $repo/install/verify-local-full.sh"
  info "Manage:      bash $ctl {start|stop|status|restart}"
}
