"""ISC DHCP include-file operations (validate, apply, rollback)."""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger("dhcp_sidecar.ops")

INCLUDE_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*\.conf$")
MAX_CONTENT_BYTES = 256 * 1024

# ISC dhcpd does not expand globs in include — we generate explicit includes here.
INCLUDES_MANIFEST_NAME = "00-clawlab-includes.conf"

DEFAULT_INCLUDES_DIR = Path("/etc/dhcp/dhcpd.d")
DEFAULT_STATE_DIR = Path("/var/lib/dhcp-sidecar")
DEFAULT_DHCPD_BIN = Path("/usr/sbin/dhcpd")
DEFAULT_SYSTEMCTL = Path("/usr/bin/systemctl")
DEFAULT_SERVICE = "isc-dhcp-server"


class DhcpSidecarError(Exception):
    def __init__(self, message: str, *, code: str = "error") -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class IncludeInfo:
    name: str
    path: str
    bytes: int
    sha256: str

    def as_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "path": self.path,
            "bytes": self.bytes,
            "sha256": self.sha256,
        }


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_file(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def validate_include_name(name: str) -> str:
    name = (name or "").strip()
    if name == INCLUDES_MANIFEST_NAME:
        raise DhcpSidecarError(
            f"{INCLUDES_MANIFEST_NAME} is reserved for the sidecar manifest",
            code="invalid_name",
        )
    if not INCLUDE_NAME_RE.fullmatch(name):
        raise DhcpSidecarError(
            "include name must match [a-zA-Z0-9][a-zA-Z0-9._-]*.conf",
            code="invalid_name",
        )
    return name


def _managed_include_paths(includes_dir: Path) -> list[Path]:
    if not includes_dir.is_dir():
        return []
    return sorted(
        path
        for path in includes_dir.glob("*.conf")
        if path.is_file() and path.name != INCLUDES_MANIFEST_NAME
    )


def regenerate_includes_manifest() -> Path:
    """Write explicit include lines for each managed *.conf (ISC dhcpd has no glob include)."""
    paths = _paths()
    includes_dir = paths["includes"]
    includes_dir.mkdir(parents=True, exist_ok=True)
    manifest = includes_dir / INCLUDES_MANIFEST_NAME
    lines = ["# Generated by dhcp-sidecar — do not edit manually"]
    for path in _managed_include_paths(includes_dir):
        lines.append(f'include "{path}";')
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return manifest


def _paths() -> dict[str, Path]:
    includes = Path(os.environ.get("DHCP_INCLUDES_DIR", str(DEFAULT_INCLUDES_DIR)))
    state = Path(os.environ.get("DHCP_SIDECAR_STATE_DIR", str(DEFAULT_STATE_DIR)))
    return {
        "includes": includes,
        "state": state,
        "staging": state / "staging",
        "backups": state / "backups",
        "audit": state / "audit.log",
    }


def ensure_state_dirs() -> None:
    p = _paths()
    for key in ("state", "staging", "backups"):
        p[key].mkdir(parents=True, exist_ok=True)
    if not p["audit"].exists():
        p["audit"].touch(mode=0o600)


def _audit(event: str, **fields: object) -> None:
    ensure_state_dirs()
    row = {"ts": _now_iso(), "event": event, **fields}
    audit_path = _paths()["audit"]
    with audit_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, sort_keys=True) + "\n")


def list_includes() -> list[IncludeInfo]:
    includes_dir = _paths()["includes"]
    out: list[IncludeInfo] = []
    for path in _managed_include_paths(includes_dir):
        out.append(
            IncludeInfo(
                name=path.name,
                path=str(path),
                bytes=path.stat().st_size,
                sha256=_sha256_file(path),
            )
        )
    return out


def read_include(name: str) -> dict[str, object]:
    name = validate_include_name(name)
    path = _paths()["includes"] / name
    if not path.is_file():
        raise DhcpSidecarError(f"include not found: {name}", code="not_found")
    content = path.read_text(encoding="utf-8")
    return {
        "name": name,
        "path": str(path),
        "content": content,
        "sha256": _sha256_bytes(content.encode("utf-8")),
    }


def _check_content_size(content: str) -> None:
    size = len(content.encode("utf-8"))
    if size == 0:
        raise DhcpSidecarError("content must not be empty", code="empty_content")
    if size > MAX_CONTENT_BYTES:
        raise DhcpSidecarError(
            f"content exceeds {MAX_CONTENT_BYTES} bytes",
            code="content_too_large",
        )


def _dhcpd_bin() -> Path:
    raw = os.environ.get("DHCPD_BIN", str(DEFAULT_DHCPD_BIN))
    path = Path(raw)
    if not path.is_file():
        raise DhcpSidecarError(f"dhcpd not found at {path}", code="dhcpd_missing")
    return path


def _systemctl_bin() -> Path:
    raw = os.environ.get("SYSTEMCTL_BIN", str(DEFAULT_SYSTEMCTL))
    path = Path(raw)
    if not path.is_file():
        raise DhcpSidecarError(f"systemctl not found at {path}", code="systemctl_missing")
    return path


def _service_name() -> str:
    return os.environ.get("DHCP_SERVICE", DEFAULT_SERVICE).strip() or DEFAULT_SERVICE


def _build_test_tree(candidate_name: str, candidate_content: str) -> tuple[Path, Path]:
    """Return (temp_root, test_dhcpd_conf) with merged include set."""
    paths = _paths()
    includes_dir = paths["includes"]
    tmp_root = Path(tempfile.mkdtemp(prefix="dhcp-sidecar-"))
    test_includes = tmp_root / "includes"
    test_includes.mkdir()
    for src in _managed_include_paths(includes_dir):
        shutil.copy2(src, test_includes / src.name)
    (test_includes / candidate_name).write_text(candidate_content, encoding="utf-8")
    test_conf = tmp_root / "dhcpd-test.conf"
    lines = [f'include "{p}";' for p in sorted(test_includes.glob("*.conf"))]
    if not lines:
        raise DhcpSidecarError("no include files to test", code="no_includes")
    test_conf.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return tmp_root, test_conf


def run_dhcpd_test(candidate_name: str, candidate_content: str) -> dict[str, object]:
    name = validate_include_name(candidate_name)
    _check_content_size(candidate_content)
    tmp_root: Path | None = None
    try:
        tmp_root, test_conf = _build_test_tree(name, candidate_content)
        dhcpd = _dhcpd_bin()
        proc = subprocess.run(
            [str(dhcpd), "-t", "-cf", str(test_conf)],
            capture_output=True,
            text=True,
            timeout=int(os.environ.get("DHCPD_TEST_TIMEOUT", "30")),
            check=False,
        )
        ok = proc.returncode == 0
        return {
            "ok": ok,
            "command": [str(dhcpd), "-t", "-cf", str(test_conf)],
            "stdout": (proc.stdout or "")[-4000:],
            "stderr": (proc.stderr or "")[-4000:],
            "returncode": proc.returncode,
        }
    except subprocess.TimeoutExpired as exc:
        raise DhcpSidecarError("dhcpd -t timed out", code="dhcpd_timeout") from exc
    finally:
        if tmp_root is not None:
            shutil.rmtree(tmp_root, ignore_errors=True)


def validate_include(name: str, content: str) -> dict[str, object]:
    name = validate_include_name(name)
    _check_content_size(content)
    result = run_dhcpd_test(name, content)
    if not result["ok"]:
        raise DhcpSidecarError(
            "dhcpd -t failed",
            code="dhcpd_test_failed",
        )
    return {"name": name, "validated": True, "dhcpd_test": result}


def _backup_dir(change_id: str) -> Path:
    safe_id = re.sub(r"[^a-zA-Z0-9._-]", "_", change_id.strip())[:128]
    if not safe_id:
        raise DhcpSidecarError("change_id is required", code="missing_change_id")
    return _paths()["backups"] / safe_id


def _write_backup_manifest(
    backup_root: Path,
    name: str,
    *,
    existed: bool,
    previous_sha: str | None,
) -> None:
    manifest_path = backup_root / "manifest.json"
    manifest: dict[str, object] = {}
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest[name] = {"existed": existed, "previous_sha256": previous_sha}
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def apply_include(
    name: str,
    content: str,
    *,
    change_id: str,
    actor: str = "api",
) -> dict[str, object]:
    name = validate_include_name(name)
    _check_content_size(content)
    test = run_dhcpd_test(name, content)
    if not test["ok"]:
        raise DhcpSidecarError("dhcpd -t failed; refusing apply", code="dhcpd_test_failed")

    paths = _paths()
    target = paths["includes"] / name
    paths["includes"].mkdir(parents=True, exist_ok=True)
    backup_root = _backup_dir(change_id)
    backup_root.mkdir(parents=True, exist_ok=True)
    backup_file = backup_root / name

    previous_sha = None
    existed = target.is_file()
    if existed:
        shutil.copy2(target, backup_file)
        previous_sha = _sha256_file(target)
    _write_backup_manifest(backup_root, name, existed=existed, previous_sha=previous_sha)

    staging = paths["staging"]
    staging.mkdir(parents=True, exist_ok=True)
    staging_file = staging / f"{change_id}-{name}"
    staging_file.write_text(content, encoding="utf-8")
    shutil.copy2(staging_file, target)
    regenerate_includes_manifest()

    live_test = run_dhcpd_test(name, content)
    if not live_test["ok"]:
        if backup_file.is_file():
            shutil.copy2(backup_file, target)
        elif target.is_file():
            target.unlink()
        raise DhcpSidecarError(
            "post-write dhcpd -t failed; rolled back file",
            code="post_write_test_failed",
        )

    reload_result = reload_service()
    _audit(
        "apply",
        change_id=change_id,
        actor=actor,
        name=name,
        previous_sha256=previous_sha,
        new_sha256=_sha256_bytes(content.encode("utf-8")),
        reload=reload_result,
    )
    return {
        "change_id": change_id,
        "name": name,
        "path": str(target),
        "applied": True,
        "previous_sha256": previous_sha,
        "sha256": _sha256_bytes(content.encode("utf-8")),
        "dhcpd_test": test,
        "reload": reload_result,
    }


def reload_service() -> dict[str, object]:
    systemctl = _systemctl_bin()
    service = _service_name()
    action = "reload"
    proc = subprocess.run(
        [str(systemctl), "reload", service],
        capture_output=True,
        text=True,
        timeout=int(os.environ.get("SYSTEMCTL_TIMEOUT", "30")),
        check=False,
    )
    if proc.returncode != 0:
        action = "restart"
        proc = subprocess.run(
            [str(systemctl), "restart", service],
            capture_output=True,
            text=True,
            timeout=int(os.environ.get("SYSTEMCTL_TIMEOUT", "60")),
            check=False,
        )
    if proc.returncode != 0:
        raise DhcpSidecarError(
            f"systemctl {action} {service} failed: {(proc.stderr or proc.stdout).strip()}",
            code="reload_failed",
        )
    active = subprocess.run(
        [str(systemctl), "is-active", service],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    return {
        "service": service,
        "action": action,
        "returncode": proc.returncode,
        "is_active": (active.stdout or "").strip(),
    }


def rollback_change(change_id: str, *, actor: str = "api") -> dict[str, object]:
    backup_root = _backup_dir(change_id)
    if not backup_root.is_dir():
        raise DhcpSidecarError(f"no backup for change_id {change_id}", code="not_found")

    manifest_path = backup_root / "manifest.json"
    if not manifest_path.is_file():
        raise DhcpSidecarError(
            f"backup manifest missing for {change_id}",
            code="manifest_missing",
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(manifest, dict) or not manifest:
        raise DhcpSidecarError(f"backup manifest empty for {change_id}", code="empty_backup")

    restored: list[str] = []
    removed: list[str] = []
    includes_dir = _paths()["includes"]

    for name, meta in manifest.items():
        validate_include_name(str(name))
        target = includes_dir / name
        existed = bool(isinstance(meta, dict) and meta.get("existed"))
        backup_file = backup_root / name
        if existed:
            if not backup_file.is_file():
                raise DhcpSidecarError(
                    f"backup file missing for {name}",
                    code="backup_missing",
                )
            shutil.copy2(backup_file, target)
            restored.append(name)
        elif target.is_file():
            target.unlink()
            removed.append(name)

    regenerate_includes_manifest()

    test_name = restored[0] if restored else None
    if test_name:
        live_path = includes_dir / test_name
        live_test = run_dhcpd_test(test_name, live_path.read_text(encoding="utf-8"))
        if not live_test["ok"]:
            raise DhcpSidecarError(
                "rollback content failed dhcpd -t; left files on disk",
                code="rollback_test_failed",
            )
    elif removed:
        # All targets removed — validate remaining tree if any includes left.
        remaining = _managed_include_paths(includes_dir)
        if remaining:
            sample = remaining[0]
            live_test = run_dhcpd_test(
                sample.name,
                sample.read_text(encoding="utf-8"),
            )
            if not live_test["ok"]:
                raise DhcpSidecarError(
                    "remaining config failed dhcpd -t after rollback",
                    code="rollback_test_failed",
                )
    reload_result = reload_service()
    _audit(
        "rollback",
        change_id=change_id,
        actor=actor,
        restored=restored,
        removed=removed,
        reload=reload_result,
    )
    return {
        "change_id": change_id,
        "restored": restored,
        "removed": removed,
        "reload": reload_result,
    }
