#!/usr/bin/env python3
"""Generate granular IOS-XE allow_groups from Cisco 17.17 CR chapter layout."""

from __future__ import annotations

import yaml

# category ids align with group_categories in ios-xe-policy.yaml
ALLOW_GROUPS: dict[str, dict] = {
    # --- VLAN (Part XIII, ch. 15) ---
    "vlan": {
        "category": "vlan",
        "description": "Create VLAN and assign name",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^vlan\s+\d+",
            r"(?i)^\s*name\s+",
        ],
    },
    "vlan_svi": {
        "category": "vlan",
        "description": "L3 SVI only (interface VlanN + ip address)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+Vlan\d+",
            r"(?i)^\s*ip\s+address\s+(?:\d{1,3}\.){3}\d{1,3}(?:\s+(?:\d{1,3}\.){3}\d{1,3}|/\d{1,2}|\s+\d{1,2})?(?:\s+secondary)?\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*shutdown\s*$",
        ],
    },
    "vlan_l3": {
        "category": "vlan",
        "description": "Create VLAN plus SVI (L3 switch / gateway)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^vlan\s+\d+",
            r"(?i)^\s*name\s+",
            r"(?i)^interface\s+Vlan\d+",
            r"(?i)^\s*ip\s+address\s+(?:\d{1,3}\.){3}\d{1,3}(?:\s+(?:\d{1,3}\.){3}\d{1,3}|/\d{1,2}|\s+\d{1,2})?(?:\s+secondary)?\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
            r"(?i)^\s*description\s+",
        ],
    },
    "private_vlan": {
        "category": "vlan",
        "description": "Private VLAN mapping (isolated/community)",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^vlan\s+\d+",
            r"(?i)^\s*private-vlan\b",
            r"(?i)^\s*name\s+",
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*switchport\s+mode\s+private-vlan\b",
            r"(?i)^\s*switchport\s+private-vlan\b",
        ],
    },
    "vtp": {
        "category": "vlan",
        "description": "VTP domain/mode/version",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^vtp\s+", r"(?i)^\s*vtp\s+"],
    },
    # --- Interface (Part III, ch. 4) ---
    "interface_l2": {
        "category": "interface",
        "description": "Access port admin state, VLAN, portfast edge",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa|Ethernet|Et)\S+",
            r"(?i)^\s*shutdown\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*switchport\s+mode\s+access\s*$",
            r"(?i)^\s*switchport\s+access\s+vlan\s+\d+",
            r"(?i)^\s*switchport\s+nonegotiate\s*$",
            r"(?i)^\s*spanning-tree\s+portfast\s+edge\s*$",
            r"(?i)^\s*spanning-tree\s+bpduguard\s+enable\s*$",
            r"(?i)^\s*speed\s+\S+",
            r"(?i)^\s*duplex\s+\S+",
        ],
    },
    "interface_trunk": {
        "category": "interface",
        "description": "Trunk mode, allowed VLANs, native VLAN",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa|Ethernet|Et)\S+",
            r"(?i)^\s*switchport\s+mode\s+trunk\s*$",
            r"(?i)^\s*switchport\s+trunk\s+",
            r"(?i)^\s*switchport\s+nonegotiate\s*$",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*shutdown\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
        ],
    },
    "voice_vlan": {
        "category": "interface",
        "description": "Access port voice VLAN (Cisco phone)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*switchport\s+mode\s+access\s*$",
            r"(?i)^\s*switchport\s+access\s+vlan\s+\d+",
            r"(?i)^\s*switchport\s+voice\s+vlan\s+",
            r"(?i)^\s*mls\s+qos\s+trust\s+",
            r"(?i)^\s*description\s+",
        ],
    },
    "interface_po": {
        "category": "interface",
        "description": "EtherChannel / port-channel (LACP/PAgP)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa|Port-channel|Po)\S+",
            r"(?i)^\s*channel-group\s+\d+",
            r"(?i)^\s*channel-protocol\s+",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*shutdown\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
            r"(?i)^\s*switchport\s+",
            r"(?i)^lacp\s+",
            r"(?i)^port-channel\s+",
        ],
    },
    "storm_control": {
        "category": "interface",
        "description": "Storm-control thresholds",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*storm-control\s+",
        ],
    },
    "lldp_cdp": {
        "category": "interface",
        "description": "LLDP/CDP on interface or globally",
        "access": "approve",
        "risk": "low",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*lldp\s+",
            r"(?i)^\s*cdp\s+",
            r"(?i)^lldp\s+run\s*$",
            r"(?i)^cdp\s+run\s*$",
            r"(?i)^no\s+cdp\s+run\s*$",
        ],
    },
    "udld": {
        "category": "interface",
        "description": "UDLD on fiber uplinks",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te)\S+",
            r"(?i)^\s*udld\s+",
            r"(?i)^udld\s+",
        ],
    },
    "macro_port": {
        "category": "interface",
        "description": "SmartPort / interface macro apply",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*macro\s+",
            r"(?i)^macro\s+",
        ],
    },
    "loopback": {
        "category": "interface",
        "description": "Loopback interface with IPv4 address",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+Loopback\d+",
            r"(?i)^\s*ip\s+address\s+",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*shutdown\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
        ],
    },
    # --- Spanning tree (Part VI, ch. 7) ---
    "spanning_tree_if": {
        "category": "spanning_tree",
        "description": "Per-interface STP cost, priority, portfast, guard",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa|Port-channel|Po)\S+",
            r"(?i)^\s*spanning-tree\s+",
        ],
    },
    "spanning_tree_global": {
        "category": "spanning_tree",
        "description": "Global STP mode (rapid-pvst/mst), root bridge",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^spanning-tree\s+",
            r"(?i)^spanning-tree\s+mst\s+configuration",
            r"(?i)^\s*instance\s+\d+",
            r"(?i)^\s*name\s+",
            r"(?i)^\s*revision\s+\d+",
        ],
    },
    # --- IP addressing (Part IV, ch. 5) ---
    "ipv6_svi": {
        "category": "ip_addressing",
        "description": "IPv6 address on SVI or routed interface",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:Vlan\d+|Loopback\d+|GigabitEthernet|Gi|TenGigabitEthernet|Te)\S*",
            r"(?i)^\s*ipv6\s+address\s+",
            r"(?i)^\s*ipv6\s+enable\s*$",
            r"(?i)^\s*no\s+shutdown\s*$",
        ],
    },
    "ip_helpers": {
        "category": "ip_addressing",
        "description": "IP helper-address (DHCP relay)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:Vlan\d+|Loopback\d+|GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa|Port-channel|Po)\S*",
            r"(?i)^\s*ip\s+helper-address(?:\s+vrf\s+\S+)?\s+",
            r"(?i)^\s*no\s+ip\s+helper-address(?:\s+vrf\s+\S+)?\s+",
            r"(?i)^ip\s+forward-protocol\s+",
            r"(?i)^no\s+ip\s+forward-protocol\s+",
        ],
    },
    "dhcp_snooping": {
        "category": "ip_addressing",
        "description": "DHCP snooping global and per-VLAN",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+dhcp\s+snooping\b",
            r"(?i)^ip\s+dhcp\s+snooping\s+vlan\s+",
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*ip\s+dhcp\s+snooping\s+",
        ],
    },
    "dhcp_pool": {
        "category": "ip_addressing",
        "description": "On-box DHCP address pool",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+dhcp\s+pool\s+",
            r"(?i)^\s*network\s+",
            r"(?i)^\s*default-router\s+",
            r"(?i)^\s*dns-server\s+",
            r"(?i)^\s*domain-name\s+",
            r"(?i)^\s*lease\s+",
        ],
    },
    "hsrp_vrrp": {
        "category": "ip_addressing",
        "description": "HSRP / VRRP first-hop redundancy",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+Vlan\d+",
            r"(?i)^\s*standby\s+",
            r"(?i)^\s*vrrp\s+",
            r"(?i)^\s*ip\s+address\s+",
        ],
    },
    # --- Routing (Part IX, ch. 10) — default deny; enable in Policy tab if needed ---
    "routing_static": {
        "category": "routing",
        "description": "Static routes (non-default)",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+route\s+(?!0\.0\.0\.0\b)\S+",
            r"(?i)^ip\s+route\s+vrf\s+\S+\s+(?!0\.0\.0\.0\b)\S+",
            r"(?i)^ipv6\s+route\s+(?!::/0\b)\S+",
        ],
    },
    "routing_default": {
        "category": "routing",
        "description": "Default route injection (0.0.0.0/0 or ::/0)",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+route\s+0\.0\.0\.0\b",
            r"(?i)^ipv6\s+route\s+::/0\b",
        ],
    },
    "routing_ospf": {
        "category": "routing",
        "description": "OSPF routing process and area/network",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^router\s+ospf\b",
            r"(?i)^\s*network\s+",
            r"(?i)^\s*area\s+",
            r"(?i)^\s*passive-interface\s+",
            r"(?i)^\s*default-information\s+",
        ],
    },
    "routing_ospfv3": {
        "category": "routing",
        "description": "OSPFv3 routing process",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^router\s+ospfv3\b", r"(?i)^\s*address-family\s+"],
    },
    "routing_bgp": {
        "category": "routing",
        "description": "BGP routing process and neighbors",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^router\s+bgp\b",
            r"(?i)^\s*neighbor\s+",
            r"(?i)^\s*network\s+",
            r"(?i)^\s*address-family\s+",
            r"(?i)^\s*bgp\s+",
        ],
    },
    "routing_eigrp": {
        "category": "routing",
        "description": "EIGRP routing process",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^router\s+eigrp\b",
            r"(?i)^\s*network\s+",
            r"(?i)^\s*passive-interface\s+",
            r"(?i)^\s*af-interface\s+",
        ],
    },
    "routing_rip": {
        "category": "routing",
        "description": "RIP routing process",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^router\s+rip\b", r"(?i)^\s*network\s+", r"(?i)^\s*version\s+"],
    },
    "routing_isis": {
        "category": "routing",
        "description": "IS-IS routing process",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^router\s+isis\b", r"(?i)^\s*net\s+", r"(?i)^\s*metric-style\s+"],
    },
    "routing_route_map": {
        "category": "routing",
        "description": "Route-map policy definitions",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^route-map\s+", r"(?i)^\s*(?:match|set)\s+"],
    },
    "routing_prefix_list": {
        "category": "routing",
        "description": "IP/IPv6 prefix-list filters",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+prefix-list\b",
            r"(?i)^ipv6\s+prefix-list\b",
            r"(?i)^\s*(?:permit|deny|seq)\s+",
        ],
    },
    "routing_redistribute": {
        "category": "routing",
        "description": "Route redistribution under routing process",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^redistribute\b"],
    },
    # --- Security / AAA (Part X, ch. 11) ---
    "aaa_core": {
        "category": "security",
        "description": "AAA new-model, authentication, authorization, accounting",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^aaa\s+new-model\s*$",
            r"(?i)^aaa\s+authentication\s+",
            r"(?i)^aaa\s+authorization\s+",
            r"(?i)^aaa\s+accounting\s+",
            r"(?i)^aaa\s+session-id\s+",
            r"(?i)^aaa\s+server\s+",
            r"(?i)^aaa\s+group\s+",
        ],
    },
    "aaa_radius": {
        "category": "security",
        "description": "RADIUS server and global RADIUS settings",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^radius\s+",
            r"(?i)^radius-server\s+",
            r"(?i)^aaa\s+group\s+server\s+radius\s+",
        ],
    },
    "aaa_tacacs": {
        "category": "security",
        "description": "TACACS+ server and global TACACS settings",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^tacacs\s+",
            r"(?i)^tacacs-server\s+",
            r"(?i)^aaa\s+group\s+server\s+tacacs\+?\s+",
        ],
    },
    "acl_standard": {
        "category": "security",
        "description": "Standard numbered/named IPv4 ACL entries",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+access-list\s+standard\s+",
            r"(?i)^access-list\s+\d+\s+",
            r"(?i)^\s*(?:permit|deny)\s+",
            r"(?i)^\s*remark\s+",
        ],
    },
    "acl_extended": {
        "category": "security",
        "description": "Extended numbered/named IPv4 ACL entries",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+access-list\s+extended\s+",
            r"(?i)^access-list\s+\d{3,}\s+",
            r"(?i)^\s*(?:permit|deny)\s+",
            r"(?i)^\s*remark\s+",
        ],
    },
    "acl_ipv6": {
        "category": "security",
        "description": "IPv6 access-list entries",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ipv6\s+access-list\s+",
            r"(?i)^\s*(?:permit|deny|sequence)\s+",
            r"(?i)^\s*remark\s+",
        ],
    },
    "acl_mac": {
        "category": "security",
        "description": "Layer-2 MAC access-list",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^mac\s+access-list\s+",
            r"(?i)^\s*(?:permit|deny)\s+",
        ],
    },
    "acl_apply": {
        "category": "security",
        "description": "Apply ACL to interface (ip/ipv6 access-group)",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|Vlan|Port-channel|Po)\S*",
            r"(?i)^\s*ip\s+access-group\s+",
            r"(?i)^\s*ipv6\s+traffic-filter\s+",
        ],
    },
    "dot1x_port": {
        "category": "security",
        "description": "802.1X / access-session on access port",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*authentication\s+",
            r"(?i)^\s*dot1x\s+",
            r"(?i)^\s*access-session\s+",
        ],
    },
    # --- QoS (Part VIII, ch. 9) ---
    "qos_class_map": {
        "category": "qos",
        "description": "Class-map match criteria",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^class-map\s+", r"(?i)^\s*match\s+"],
    },
    "qos_policy_map": {
        "category": "qos",
        "description": "Policy-map classes and actions",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^policy-map\s+",
            r"(?i)^\s*class\s+",
            r"(?i)^\s*priority\b",
            r"(?i)^\s*police\s+",
            r"(?i)^\s*shape\s+",
            r"(?i)^\s*bandwidth\s+",
            r"(?i)^\s*set\s+",
        ],
    },
    "qos_service_policy": {
        "category": "qos",
        "description": "Apply service-policy on interface or control-plane",
        "access": "approve",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|FastEthernet|Fa)\S+",
            r"(?i)^\s*service-policy\s+",
            r"(?i)^control-plane\b",
            r"(?i)^\s*service-policy\s+",
        ],
    },
    "qos_auto_mls": {
        "category": "qos",
        "description": "Auto QoS and MLS QoS trust settings",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^auto\s+qos\s+",
            r"(?i)^\s*mls\s+qos\s+",
            r"(?i)^mls\s+qos\s+",
        ],
    },
    # --- Network management (Part VII, ch. 8) ---
    "logging_syslog": {
        "category": "netmgmt",
        "description": "Syslog hosts, severity, source-interface",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^logging\s+",
            r"(?i)^service\s+timestamps\s+",
        ],
    },
    "snmp_traps": {
        "category": "netmgmt",
        "description": "SNMP traps, location, contact (not communities)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^snmp-server\s+host\s+",
            r"(?i)^snmp-server\s+enable\s+traps\s+",
            r"(?i)^snmp-server\s+location\s+",
            r"(?i)^snmp-server\s+contact\s+",
        ],
    },
    "netflow_exporter": {
        "category": "netmgmt",
        "description": "Flexible NetFlow exporter definition",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^flow\s+exporter\s+",
            r"(?i)^\s*description\s+",
            r"(?i)^\s*destination\s+",
            r"(?i)^\s*transport\s+",
        ],
    },
    "netflow_record": {
        "category": "netmgmt",
        "description": "Flexible NetFlow record (collect/match fields)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^flow\s+record\s+",
            r"(?i)^\s*match\s+",
            r"(?i)^\s*collect\s+",
        ],
    },
    "netflow_monitor": {
        "category": "netmgmt",
        "description": "Flexible NetFlow monitor (record + exporter)",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^flow\s+monitor\s+",
            r"(?i)^\s*record\s+",
            r"(?i)^\s*exporter\s+",
            r"(?i)^\s*cache\s+",
        ],
    },
    "netflow_interface": {
        "category": "netmgmt",
        "description": "Apply NetFlow monitor on interface",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^interface\s+(?:GigabitEthernet|Gi|TenGigabitEthernet|Te|Vlan)\S*",
            r"(?i)^\s*ip\s+flow\s+monitor\s+",
            r"(?i)^\s*ip\s+flow\s+ingress\s+",
            r"(?i)^\s*ip\s+flow\s+egress\s+",
        ],
    },
    "dns_ntp": {
        "category": "netmgmt",
        "description": "DNS domain/name-server and NTP sources",
        "access": "approve",
        "risk": "low",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+domain-name\s+",
            r"(?i)^ip\s+name-server\s+",
            r"(?i)^ip\s+domain\s+lookup\s+",
            r"(?i)^ntp\s+server\s+",
            r"(?i)^ntp\s+source\s+",
            r"(?i)^ntp\s+authenticate\s+",
            r"(?i)^clock\s+timezone\s+",
        ],
    },
    # --- System (Part XII, ch. 13) ---
    "hostname_banner": {
        "category": "system",
        "description": "Hostname and login/MOTD banners",
        "access": "approve",
        "risk": "low",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^hostname\s+", r"(?i)^banner\s+"],
    },
    "errdisable": {
        "category": "system",
        "description": "Errdisable detect/recovery causes and timers",
        "access": "approve",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^errdisable\s+"],
    },
    # --- Multicast (Part V, ch. 6) ---
    "multicast_pim": {
        "category": "multicast",
        "description": "PIM sparse/dense and RP configuration",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+pim\s+",
            r"(?i)^ipv6\s+pim\s+",
            r"(?i)^ip\s+multicast-routing\b",
            r"(?i)^ipv6\s+multicast-routing\b",
        ],
    },
    "multicast_igmp": {
        "category": "multicast",
        "description": "IGMP/MLD snooping querier settings",
        "access": "deny",
        "risk": "medium",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^ip\s+igmp\s+",
            r"(?i)^ipv6\s+mld\s+",
            r"(?i)^\s*ip\s+igmp\s+",
        ],
    },
    # --- Fabric / advanced ---
    "sd_access": {
        "category": "fabric",
        "description": "Cisco SD-Access / LISP fabric",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^lisp\s+", r"(?i)^fabric\s+", r"(?i)^extranet\s+"],
    },
    "trustsec": {
        "category": "fabric",
        "description": "Cisco TrustSec / CTS / SXP",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [r"(?i)^cts\s+", r"(?i)^\s*cts\s+"],
    },
    "stacking": {
        "category": "fabric",
        "description": "Stack / switch-number / StackWise Virtual",
        "access": "deny",
        "risk": "high",
        "defenseclaw_alert": True,
        "patterns": [
            r"(?i)^switch\s+\d+\s+",
            r"(?i)^stackwise-virtual\b",
            r"(?i)^hw-module\s+switch\s+\d+\s+",
        ],
    },
}

# Backward-compatible alias used in forms and docs
ALLOW_GROUPS["static_route"] = ALLOW_GROUPS["routing_static"]

if __name__ == "__main__":
    print(yaml.safe_dump({"allow_groups": ALLOW_GROUPS}, sort_keys=False, default_flow_style=False))
