#!/usr/bin/env bash
# Copy maintainer-only paths into ./_archive/ before removing them from the public tree.
# Safe to re-run; overwrites prior copies.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
ARCHIVE="$REPO/_archive"
MANIFEST="$ARCHIVE/MANIFEST.txt"

# Paths relative to repo root (files or directories).
ARCHIVE_PATHS=(
  admin-access/alice
  admin-access/training-network-specialist
  admin-access/scrub-public-release.py
  admin-access/apply-trusted-proxy.py
  admin-access/openclaw.trusted-proxy.json5
  admin-access/pam-openclaw-admin
  admin-access/openclaw-admin.nginx.conf
  dhcp-sidecar
  isc-dhcp-mcp
  mcp-port
  model-tiering
)

mkdir -p "$ARCHIVE"
: >"$MANIFEST"
printf '# Generated by populate-maintainer-archive.sh\n' >>"$MANIFEST"

for rel in "${ARCHIVE_PATHS[@]}"; do
  src="$REPO/$rel"
  if [[ ! -e "$src" ]]; then
    echo "skip (missing): $rel" >&2
    continue
  fi
  dest="$ARCHIVE/$rel"
  mkdir -p "$(dirname "$dest")"
  if [[ -d "$src" ]]; then
    rm -rf "$dest"
    cp -R "$src" "$dest"
  else
    cp "$src" "$dest"
  fi
  echo "$rel" >>"$MANIFEST"
  echo "archived: $rel"
done

echo "Done — see $ARCHIVE"
